version: '3.7'

services:
  api:
    build:
      context: ./docker
      dockerfile: Dockerfile
    command: ["yarn", "dev"]
    ports:
      - 8081:8080
    volumes:
      - ./:/app
    working_dir: /app